### ISSUE TITLE
DSP usage

### ISSUE THREAD

**Issue by wolfhai** [ssj71/reMID.lv2#3] opened 2019-01-27 09:49 UTC
Hi,

Great Plugin. Thanks you.

I used it with Ardour 5.12.0 on Debian stretch.
But after playing several notes, the Digital Signal Processing rises up to 87% and doesn't drop down anymore.

I noticed that the Master output detects a signal which is not hearable even than, when no note is played.

It seems the plugin is constantly processing.
When I change the instrument file, the DSP drops down to a normal standby value.

**Comment by ssj71** [comment] 2019-01-28 16:48
Thanks for using and for the report.

What patch are you using to produce this? Just the default? Could you record a little bit of the signal that you can't hear but the meter shows, and paste an image of the waveform for me to see? It may provide some insight. I'm not sure when I'll have time to address this, but hopefully I can look into it this week sometime.

**Comment by wolfhai** [comment] 2019-01-28 18:57
Thanks for your reply.

I used the default patch, but it occurs with any other instrument.

As you see in the enclosed screenshots the audio level rises each time.
After changing the patch, the audio level drops back to normal.

The plugin was build on Debian stretch with the instructions on github.

"
Once the dependencies are fulfilled return to this folder and run:
   mkdir build
   cd build
   cmake ..
   make
   sudo make install
"

Again, thanks a lot for this plugin and for publishing the source code. I like the sound as former Commodore 64 user very much.

Greetings

**Comment by ssj71** [comment] 2019-01-28 19:03
I think the attachments don't upload to github unfortunately. Could you load them to imgur or snag.gy or equivalent and link them? 

Thanks!

**Comment by wolfhai** [comment] 2019-01-28 19:13
No problem
https://imgur.com/a/XaTSWHd

**Comment by ssj71** [comment] 2019-01-28 19:44
ok, thats like I expected. there's a DC offset. which is why the meters
show a signal. Thats not really a problem in many cases, but I think I'll add a DC removal filter.

Unfortunately that doesn't tell me why the DSP load doesn't
drop. I suspect the filter simulation still runs even when the note is
silenced. I'll have to dig into it. Thanks again!

**Comment by ssj71** [comment] 2019-01-28 19:58
ok, I was feeling like a short break from work and looked into it. It is in fact 1 problem not 2, the DC offset is causing the notes to not deactivate when they are complete. I'll have to figure out the best approach to resolve, but now I'm pretty confident in the cause which is half the battle! :)

**Comment by ssj71** [comment] 2019-01-30 00:18
I have implemented the blocking filter on the dev branch, which should theoretically resolve this, but I am not in a place where I can test it ATM. If you are brave you can do so yourself, and I'd appreciate learning what you find. If not I will try to test in the next few days.

**Comment by wolfhai** [comment] 2019-01-30 04:57
Tried the lv2 plugin and the jack standalone version.
Also changed the default preset with Ardour.
Both segfaults as soon as I try to play a tune.

...
$ ./reMID
Opening JACK MIDI port
loading instruments.conf
Configuration file format: 0.000000
loading instrument: piano
loading instrument: piano2
loading instrument: harpsichord
loading instrument: organ
loading instrument: bass_big0c
loading instrument: test
loading instrument: test2
loading instrument: test3
loading instrument: test-percussion
loading instrument: bass_drum2
loading instrument: bass_drum1
loading instrument: snare_drum1
12 instruments loaded from instruments.conf
32 reSID chip polyphony system
524288 bytes free in SID output buffer
The sample rate is now 48000 /sec
PAL mode: clock frequency 985248.00, frequency multiplier 0.058725

READY.
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
Segmentation fault
...

**Comment by ssj71** [comment] 2019-01-30 07:32
Well thanks for being a brave tester 😀 untested code never works the first time. It's probably something simple but I will have to try to look at it tomorrow night when I can test it at home. Thanks for your patience.

**Comment by ssj71** [comment] 2019-02-02 06:00
ok, I did make a really dumb error. But I finally took the time to fix it. Pelase confirn with the dev branch and I'll merge it into master. This at least resolves the CPU problem. Let me know if you think the sound has been compromised at all. Thanks again for being patient and for the bug report!

**Comment by wolfhai** [comment] 2019-02-02 07:19
Couldn't hear any difference in sound in a short test.

When I start Ardour, the DSP value drops down to 2% on idle, my Linux box isn't very fast.
After playing some tones, the DSP value drops down to arround 8% on idle.
I did the same test with JuceOPL lv2 and this plugin drops down to the idle DSP value 2% again.

Can't really tell if the 8% are caused by my slow hardware or if there is something still processing in the background?

Thanks

**Comment by wolfhai** [comment] 2019-02-02 07:34
I just tested the standalone version.
Hope it helps.

this is the top command output in idle mode:
PID  USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+  COMMAND
5085 user      20   0  167140  86260  85224 S   6.0  2.6   0:03.08  reMID

**Comment by ssj71** [comment] 2019-02-03 06:08
I had noticed that but didn't think much of it. Since you insisted I dug into it and found some other bugs. :) I've gone ahead and merged the dev branch into master. Please give it a try and let me know if you have any other issues. As always, many thanks for your participation.

p.s. I do most of my development on a 2008 core2 duo so I understand a bit about slow hardware :)

**Comment by wolfhai** [comment] 2019-02-03 08:09
Looks good, sounds great, wonderful.

Thank you very much.

**Comment by ssj71** [comment] 2019-02-04 17:51
if you make any great patches, please share and I'll include them as presets :)

**Closed as completed** 2019-02-04 17:50 UTC
